sudo: false
dist: trusty
language: perl
perl:
  - "5.24"
  - "5.22"
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
install:
  - "cpanm -n Mojolicious DBI Mojo::Pg EV IO::Socket::Socks IO::Socket::SSL Net::DNS::Native Test::Perl::Critic Test::Pod Test::Pod::Coverage"
  - "cpanm --quiet --installdeps --notest ."
services:
  - memcached
  - redis-server
  - postgresql
addons:
  hosts:
    - helptasker.net
  postgresql: "9.5"
env:
  - "MOJO_TEST=1"
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
notifications:
  email:
    on_success: always
    on_failure: always
    recipients:
      - kostya@yandex.ru

# https://github.com/travis-ci/apt-package-whitelist/blob/master/ubuntu-precise
