Received: from mxfront6g.mail.yandex.net ([127.0.0.1])
	by mxfront6g.mail.yandex.net with LMTP id AaKFAjMT
	for <kostya@yandex.com>; Fri, 16 Sep 2016 10:49:37 +0300
Received: from static.mcs.mts-nn.ru (static.mcs.mts-nn.ru [82.208.102.94])
	by mxfront6g.mail.yandex.net (nwsmtp/Yandex) with ESMTP id wsnvn6qaLW-nb0u7m0v;
	Fri, 16 Sep 2016 10:49:37 +0300
Return-Path: rostelecom@rm.volga.rt.ru
X-Yandex-Front: mxfront6g.mail.yandex.net
X-Yandex-TimeMark: 1474012177
Message-Id: <20160916104937.nb0u7m0v@mxfront6g.mail.yandex.net>
Authentication-Results: mxfront6g.mail.yandex.net; spf=softfail (mxfront6g.mail.yandex.net: transitioning domain of rm.volga.rt.ru does not designate 82.208.102.94 as permitted sender) smtp.mail=rostelecom@rm.volga.rt.ru
X-Yandex-Spam: 1
Received: from 10.68.233.74 (unknown [10.78.67.181])
	by mcs.mts-nn.ru (Postfix) with SMTP id 32168141D4F
	for <kostya@yandex.com>; Fri, 16 Sep 2016 10:49:37 +0300 (MSK)
Date: Fri, 16 Sep 2016 10:49:37
From: "ПАО "Ростелеком"" <rostelecom@rm.volga.rt.ru>
To: kostya@yandex.com
Subject: =?windows-1251?B?z8DOICLQ7vHy5evl6u7sIiDo7fTu8Ozo8O7i4O3o5SDuIOfg5O7r5uXt7e7x8ug=?=
MIME-Version: 1.0
Content-Type: multipart/mixed; 
 boundary= "3C9B9523C7D007F1E053B5434E0A9E73"
X-Yandex-Forward: 3197865dad8c37047cfd352ff5bd56f3

--3C9B9523C7D007F1E053B5434E0A9E73
Content-Type: text/html; charset="windows-1251"



Уважаемый клиент!<p>
Просим пополнить счет на сумму 1200.51 руб., за услуги связи во избежание ограничения доступа  до полного погашения задолженности.<p>
Номер Вашего лицевого счета 850012841752.<p>
Оплатить счет Вы можете любым удобным для Вас способом, в т. ч. на сайте www.rt.ru, в Личном кабинете, через банкоматы, терминалы, платежные Интернет - системы, в отделениях банков и офисах компаний-партнеров (подробная информация о способах оплаты представлена на сайте www.rt.ru).<p>
С уважением, ПАО "Ростелеком"



--3C9B9523C7D007F1E053B5434E0A9E73--

.

