Received: from mxfront7o.mail.yandex.net ([127.0.0.1])
	by mxfront7o.mail.yandex.net with LMTP id bO7leHQI
	for <kostya@yandex.ru>; Thu, 18 Aug 2016 19:55:16 +0300
Received: from mta12.e.ea.com (mta12.e.ea.com [136.147.183.217])
	by mxfront7o.mail.yandex.net (nwsmtp/Yandex) with ESMTPS id 000rkVEhln-tFCqdYJc;
	Thu, 18 Aug 2016 19:55:15 +0300
	(using TLSv1.2 with cipher ECDHE-RSA-AES128-GCM-SHA256 (128/128 bits))
	(Client certificate not present)
Return-Path: bounce-18_HTML-119274180-2630-7229410-1455779@bounce.e.ea.com
X-Yandex-Front: mxfront7o.mail.yandex.net
X-Yandex-TimeMark: 1471539315
Authentication-Results: mxfront7o.mail.yandex.net; spf=pass (mxfront7o.mail.yandex.net: domain of bounce.e.ea.com designates 136.147.183.217 as permitted sender) smtp.mail=bounce-18_HTML-119274180-2630-7229410-1455779@bounce.e.ea.com; dkim=pass header.i=EA@e.ea.com
X-Yandex-Spam: 1
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; s=200608; d=e.ea.com;
 h=From:To:Subject:Date:MIME-Version:Message-ID:Content-Type:Content-Transfer-Encoding; i=EA@e.ea.com;
 bh=kwhiz5nDdg0Pf8M1ifiMkAtigPo=;
 b=sT0ZcgZpWv8Xip887xwJf1DRussGHclgLFw5KNzIbJiNjPGix/19hLcWFilYFeYtetMtH3dv8U+X
   iAET/3pxiZw3pURmVL0K7TS8NAC8yyvb2u8fwN1LUYUds5tjuxRxy/Yu7R58BXm9P310vwK51Q/F
   hWPCO+lVxrBQ+webA2A=
Received: by mta12.e.ea.com id hmnk76163hsc for <kostya@yandex.ru>; Thu, 18 Aug 2016 16:55:13 +0000 (envelope-from <bounce-18_HTML-119274180-2630-7229410-1455779@bounce.e.ea.com>)
From: "EA" <EA@e.ea.com>
To: <kostya@yandex.ru>
Subject: =?UTF-8?B?0J/QsNGA0L7Qu9GMINGD0YHQv9C10YjQvdC+INC+0LHQvdC+0LI=?=
 =?UTF-8?B?0LvQtdC9?=
Date: Thu, 18 Aug 2016 10:55:14 -0600
MIME-Version: 1.0
x-job: 7229410_2630
Message-ID: <11490921-8f31-40b4-9fe0-54b3ad96e68f@atl1s07mta646.xt.local>
Content-Type: text/html;
	charset="utf-8"
Content-Transfer-Encoding: 8bit
X-Yandex-Forward: 3197865dad8c37047cfd352ff5bd56f3

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN">
<html xmlns="http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<head>
	<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0"/>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
	<title></title>
	<link href='https://fonts.googleapis.com/css?family=Lato:400,400italic,700,700italic' rel='stylesheet' type='text/css'>
	<style type="text/css">

		/** RESET STYLES **/
		p{margin:1em 0;} /*Yahoo paragraph fix*/
		table td{border-collapse:collapse;} /*This resolves the Outlook 07, 10, and Gmail td padding issue fix*/ 
		img, a img{border:0; height:auto; outline:none; text-decoration:none;} /* Remove the borders that appear when linking images with "border:none" and "outline:none" */
		@-ms-viewport{width: device-width;}
		h1, h2, h3, h4, h5, h6{display:block !important; margin:0 !important; padding:0 !important;}
		body,{height:100% !important; -webkit-text-size-adjust:100%; -ms-text-size-adjust:100 margin:0; padding:0; width:100% !important;} /* Prevent Webkit and Windows Mobile platforms from changing default font sizes, while not breaking desktop design. */
		linkfix a {color: #bababa !important; text-decoration: none;}
		
		/** CLIENT-SPECIFIC STYLE **/
		img{-ms-interpolation-mode: bicubic;} /* Force IE to smoothly render resized images. */
		table{mso-table-lspace:0pt; mso-table-rspace:0pt;} /* Remove spacing between tables in Outlook 2007 and up. */
		.ReadMsgBody{width:100%;} .ExternalClass{width:100%;} /* Force Outlook.com to display emails at full width. */
		p, a, li, td, blockquote{mso-line-height-rule:exactly;} /* Force Outlook to render line heights as they're originally set. */
		a[href^="tel"], a[href^="sms"]{color:inherit; cursor:default; text-decoration:none;} /* Force mobile devices to inherit declared link styles. */
		p, a, li, td, body, table, blockquote{-ms-text-size-adjust:100%; -webkit-text-size-adjust:100%;} /* Prevent Windows- and Webkit-based mobile platforms from changing declared text sizes. */
		.ExternalClass, .ExternalClass p, .ExternalClass td, .ExternalClass div, .ExternalClass span, .ExternalClass font{line-height:100%;} /* Force Outlook.com to display line heights normally. */
		
		/** STRUCTURAL STYLES **/
		
		/** CONTENT STYLES **/
		body {
			width: 100%;
			background-color: #e8e8e8; 
			margin:0 auto;
			padding:0; 
			-webkit-font-smoothing: antialiased;
			font-family:"Arial", sans-serif !important;
		}
		
		/** MOBILE STYLES **/
		@media only screen and (max-device-width: 480px), screen and (max-width: 480px) {
			/* CLIENT-SPECIFIC STYLES */
			/* Template Shell */
			body[yahoo] {
				width:100% !important; 
				min-width:100% !important; 
				margin: 0 auto !important;
			} /* Force iOS Mail to render the email at full width & removes margins. */
			
			
			/*** STRUCTURAL ***/
			
			body[yahoo] .container { width: 100% !important; max-width: 480px !important; }
			body[yahoo] .mobileShow { display: block !important; margin:0 !important; padding:0 !important; overflow: visible !important; width: auto !important; max-height:inherit !important;}
			body[yahoo] .mobileHide { display:none !important; }
			body[yahoo] .photo img { width: 100% !important; max-width:100% !important; height: auto !important; }	
			body[yahoo] .columnStack { width:100% !important; display: block !important;}
			body[yahoo] .contentCenter, body[yahoo] .contentCenter img, body[yahoo] .contentCenter table { margin: 0 auto !important; }
			body[yahoo] .textCenter { text-align: center !important; }
			body[yahoo] .textLeft { text-align: left !important; }
			body[yahoo] .nullBorder { border: none !important; }
			body[yahoo] .alignTop { vertical-align: top !important;}
			body[yahoo] .autoHeight {height: auto !important;}
		   
			/*** PADDING ***/
			 
			body[yahoo] .nullPad { padding: 0px !important; } 
			body[yahoo] .mobilePad { padding-right: 30px !important; padding-left: 30px !important; }
			body[yahoo] .bottomPad5 { padding-bottom: 5px !important; } 
			body[yahoo] .topPad5 { padding-bottom: 5px !important; }
			body[yahoo] .topPad10 { padding-top: 10px !important; }
			body[yahoo] .bottomPad10 { padding-bottom: 10px !important; }
			body[yahoo] .topPad15 { padding-top: 15px !important; }
			body[yahoo] .bottomPad15 { padding-bottom: 15px !important; }
			body[yahoo] .topPad20 { padding-top: 20px !important; }
			body[yahoo] .bottomPad20 { padding-bottom: 20px !important; }
			body[yahoo] .topPad25 { padding-top: 25px !important; }
			body[yahoo] .bottomPad25 { padding-bottom: 25px !important; }
			body[yahoo] .bottomPad30 { padding-bottom: 30px !important; }
			body[yahoo] .rightPad30 { padding-right: 30px !important; }
			
			/*** FONT RESIZING ***/
			
			body[yahoo] .fontResize17 { font-size: 17px !important; }
			
		}			

		
</style>

<!--[if gte mso 9]>
<style>
    /* Target Outlook 2007 and 2010 */
			html, body { font-family: Arial, sans-serif !important; }  
			table { font-family: Arial, sans-serif !important; }  
			td { font-family: Arial, sans-serif !important; }
</style>
<![endif]-->

</head><body style="margin: 0px; -webkit-text-size-adjust:none; background-color: #dddddd;" yahoo="fix">

	
	<img src="http://click.e.ea.com/open.aspx?ffcb10-ff3416767664-fe3715717c61047f761572-fe961372776d007c75-ff961578-fe2e15717c660379741c70-fe8915747061037a7c" width="1" height="1">
	<!-- Start of: Header--> 
	<table cellpadding="0" cellspacing="0" border="0" width="100%">
		<tr>
			<td align="center" bgcolor="#dddddd" style="padding: 0px 20px;" class="nullPad">
				<table border="0" cellspacing="0" cellpadding="0" width="600" class="container">
					<tr>
						<td align="center" bgcolor="#ffffff">
							<!-- Start of: EA Header -->
<table border="0" cellspacing="0" cellpadding="0" width="100%">
	<tr>
		<td align="center" valign="middle" style="padding: 13px 40px;" class="mobilePad">
			<table border="0" cellspacing="0" cellpadding="0" width="100%">
				<tr>
					<td align="left" valign="middle">
						<a href="##" alias="EA Logo - Header" target="_blank"><img alt="EA" src="http://image.e.ea.com/lib/fe8f13727664017572/m/1/Transactional_EA_Logo.png" width="53" height="53" border="0" style="display: block;" /></a>
					</td>
					<td align="right" valign="middle" style="font-family: 'Arial', sans-serif; font-size: 10px; line-height: 10px; color: #808285;" class="mobileHide">
						<a href="http://view.e.ea.com/?qs=e2d0ac83a9225795ac24c3412dc5404a894e79c072177143c57d3d07446daf7ce5a1cf41479ad85484e2619f699f737412866e7dd61459499b0e2c64a6b97ea07e6b1c4c1885d1ec"  target="_blank" style="color: #808285; text-decoration: underline;">Для просмотра в браузере нажмите здесь. </a>
					</td>
					
				</tr>
			</table>
		</td>
		
	</tr>
</table>
<!-- End of: EA Header -->
						</td>
					</tr>
				</table>
			</td>
		</tr>
	</table>
	<!-- End of: Header -->
	<!-- Start of: Content --> 
	<table cellpadding="0" cellspacing="0" border="0" width="100%">
		<tr>
			<td align="center" bgcolor="#dddddd" style="padding: 0px 20px;" class="nullPad">
				<table border="0" cellspacing="0" cellpadding="0" width="600" class="container">
					<tr>
						<td align="center" bgcolor="#ffffff">
							<!-- Start of: Password Reset -->
<table border="0" cellspacing="0" cellpadding="0" width="100%">
	<tr>
		<td align="left" valign="top" width="100%" style="font-family: 'Arial', sans-serif; font-size: 14px; mso-line-height-rule: exactly; line-height: 22px; color: #939598; padding: 30px 30px 30px;" class="mobilePad">
			<span style="color: #000000;"><b>Здравствуйте, tenkostya!</b></span><br><br>
			Ваш пароль был успешно обновлен.<br><br>
			Если вы не отправляли запрос на изменение пароля или считаете, что получили это письмо по ошибке, пожалуйста, незамедлительно свяжитесь со службой <a href="http://click.e.ea.com/?qs=bfd07f01f76d5b9f3e8490c45ac671d6421518c38f474ec68d0f554f9cce731a75950adab48562b7"  target="_blank" style="color: #4dafd4; text-decoration: none;"><b>Справки EA</b></a> .<br><br>
			Хороших вам игр!<br> Команда EA
		</td>
	</tr>
</table>
<!-- End of: Password Reset -->
						</td>
					</tr>
				</table>
				<table border="0" cellspacing="0" cellpadding="0" width="600" class="container">
					<tr>
						<td align="center" bgcolor="#ffffff">
							
						</td>
					</tr>
				</table>
				<table border="0" cellspacing="0" cellpadding="0" width="600" class="container">
					<tr>
						<td align="center" bgcolor="#ffffff">
							
						</td>
					</tr>
				</table>
				<table border="0" cellspacing="0" cellpadding="0" width="600" class="container">
					<tr>
						<td align="center" bgcolor="#ffffff">
							
						</td>
					</tr>
				</table>
			</td>
		</tr>
	</table>
	<!-- End of: Content -->
	<table cellpadding="0" cellspacing="0" border="0" width="100%">
		<tr>
			<td align="center" bgcolor="#dddddd" style="padding: 0px 20px;" class="nullPad">
				<table cellpadding="0" cellspacing="0" border="0" width="600" class="container">
					<tr>
						<td align="center" bgcolor="#ffffff" height="1" style="font-size: 0px; mso-line-height-rule: exactly; line-height: 1px; height: 1px; padding: 0px 30px;" class="mobilePad">
							<table cellpadding="0" cellspacing="0" border="0" width="100%">
								<tr>
									<td align="center" bgcolor="#dddddd" height="1" style="font-size: 0px; mso-line-height-rule: exactly; line-height: 1px; height: 1px;">
										&nbsp;
									</td>
								</tr>
							</table>
						</td>
					</tr>
				</table>
			</td>
		</tr>
	</table>
	<!-- Start of: Footer --> 
	<table cellpadding="0" cellspacing="0" border="0" width="100%">
		<tr>
			<td align="center" bgcolor="#dddddd" style="padding: 0px 20px;" class="nullPad">
				<table border="0" cellspacing="0" cellpadding="0" width="600" class="container">
					<tr>
						<td align="center" bgcolor="#ffffff">
							<!-- Start of: EA Footer-->
<table border="0" cellspacing="0" cellpadding="0" width="100%">
	<tr>
		<td align="left" valign="top" width="100%" style=" padding: 30px;" class="mobilePad">
			<table border="0" cellspacing="0" cellpadding="0" width="100%">
				<tr>
					<td align="left" valign="top" style="font-family: 'Arial', sans-serif; font-size: 11px; mso-line-height-rule: exactly; line-height: 12px; color: #939598; padding-bottom: 12px;">
						
						Если вам требуется техническая консультация, пожалуйста, обратитесь в службу  <a href="http://click.e.ea.com/?qs=bfd07f01f76d5b9f72d3ca73c3a0658a41a98b34e83569d08120ea55e33d77d59704805a987ae25d"  target="_blank" style="color: #4dafd4; text-decoration: none;"><b>Справки EA</b></a>.<br>
					</td>
				</tr>
				<tr>
					<td align="left" valign="top" style="font-family: 'Arial', sans-serif; font-size: 11px; mso-line-height-rule: exactly; line-height: 12px; color: #939598;">
						ПОЛИТИКА КОНФИДЕНЦИАЛЬНОСТИ: наша официальная Политика конфиденциальности гарантирует вам безопасность, когда вы играете в игры EA. Чтобы просмотреть полный текст Правил соблюдения конфиденциальности информации и идентификации пользователя, зайдите на <a href="http://click.e.ea.com/?qs=bfd07f01f76d5b9ff1c1219be53c5fd9150670c239eaefd9f16e5fc4b39e46e22e1091083cc734b9"  target="_blank" style="color: #4dafd4; text-decoration: none;"><b>privacy.ea.com/ru</b></a>  или напишите по адресу: EA Swiss Sarl, Place du Molard 8, Geneva 1204, Швейцария.<br><br>
						© 2016Electronic Arts Inc. All Rights Reserved.<br>
						
						<a href="http://click.e.ea.com/?qs=bfd07f01f76d5b9f4bde9857434953e004152879efc3725d8dc784e8fff471cbb7fa3dedb3d372bdc349ace0d114bf9a"  target="_blank" style="color: #4dafd4; text-decoration: none;"><b>О компании</b></a> |
						
						<a href="http://click.e.ea.com/?qs=bfd07f01f76d5b9fe91194fa592e09cc14a1b7c42df45fd53054e06c582dd0f0189e400482e571d76875a2d79f704460"  target="_blank" style="color: #4dafd4; text-decoration: none;"><b>Правила соблюдения конфиденциальности информации и идентификации пользователя</b></a> |
						
						<a href="http://click.e.ea.com/?qs=bfd07f01f76d5b9fb279ea90fdff7d2f0efa63cd0486c56d007a738cabc0dfdeb222732add3c59d79a40058f57ef94c2"  target="_blank" style="color: #4dafd4; text-decoration: none;"><b>Соглашение об услугах</b></a> |
						
						<a href="http://click.e.ea.com/?qs=bfd07f01f76d5b9f69be2091d3276293920f6376285fcb2873f9a9bbd6342e88e3805e98c99b2cf615d227f8406e09d1"  target="_blank" style="color: #4dafd4; text-decoration: none;"><b>Правовая информация</b></a> 
						
					</td>
				</tr>
				<tr>
					<td align="left" valign="middle" style="padding: 12px 0px">
						<a href="http://click.e.ea.com/?qs=bfd07f01f76d5b9ff9436bc988ceb203279d49e7e210e5c4db8570b7913c5d969c3c1345f2ed767a"  target="_blank"><img alt="EA | Origin" src="http://image.e.ea.com/lib/fe8f13727664017572/m/1/Transactional_EA_Origin_Footer_Logos.png" width="97" height="26" border="0" style="display: block;" /></a>
					</td>
				</tr>
				<tr>
					<td align="left" valign="top" style="font-family: 'Arial', sans-serif; font-size: 11px; mso-line-height-rule: exactly; line-height: 12px; color: #939598; ">
						Origin является частью EA Network
					</td>
				</tr>
			</table>
		</td>
	</tr>
</table>
<!-- End of: EA Footer -->
						</td>
					</tr>
				</table>
				<table border="0" cellspacing="0" cellpadding="0" width="600" class="container">
					<tr>
						<td align="center" bgcolor="#ffffff">
							
						</td>
					</tr>
				</table>
			</td>
		</tr>
	</table>
	<!-- End of: Footer -->
	<table cellpadding="0" cellspacing="0" border="0" width="100%">
		<tr>
			<td align="center" bgcolor="#dddddd" height="50" style="font-size: 0px; mso-line-height-rule: exactly; line-height: 50px; height: 50px;">
				&nbsp;
			</td>
		</tr>
	</table>
	<!-- Start of : keep gmail android from collapsing table -->
	<table align="center" border="0" cellpadding="0" cellspacing="0" width="620" class="mobileHide">
		<tr>
			<td height="1" style="font-size: 1px; line-height: 1px; min-width: 620px;">&nbsp;</td>
		</tr>
	</table>
	<!-- End of : keep gmail android from collapsing table -->

</body></html>
